<?php

use Drupal\Core\Url;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_cron()
 */
function views_entity_reference_cron() {
  $view_manager = Drupal::service('views_entity_reference.sql_view_manager');
  // Just refresh SQL VIEWS for entity reference fields as necessary
  // TODO: Use Queue API?
  $list = $view_manager->refresh();
}

/**
 * Implements hook_ENTITY_TYPE_insert()
 */
function views_entity_reference_field_storage_config_insert(FieldStorageConfig $entity) {
  if ($entity->get('type') == 'entity_reference') {
    $view_manager = Drupal::service('views_entity_reference.sql_view_manager');
    $list = $view_manager->refresh($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete()
 */
function views_entity_reference_field_storage_config_delete(FieldStorageConfig $entity) {
  if ($entity->get('type') == 'entity_reference') {
    $view_manager = Drupal::service('views_entity_reference.sql_view_manager');
    $list = $view_manager->refresh();
  }
}

/**
 * Implements hook_rebuild()
 */
function views_entity_reference_rebuild() {
  $view_manager = Drupal::service('views_entity_reference.sql_view_manager');
  $list = $view_manager->refresh();
}
