views_entity_reference.settings:
  type: config_object
  label: 'VER Settings'
  mapping:
    enabled_entity_references:
      type: sequence
      label: 'Enabled entity references'
      sequence:
        type: string
        label: 'Entity'
    entity_reference_fields:
      type: sequence
      label: 'Entity reference fields'
      sequence:
        type: sequence
        label: 'Fields per entity type'
        sequence:
          type: string
          label: 'Field'

